#!/bin/usr/env bash
# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself).

# Updates Packages before making Installations
sudo apt-get update
sudo apt-get -y install nginx

# Configures the Uncomplicated Firewall (UFW) to allow incoming traffic for the Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creates an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Tests Nginx configurations for Syntax errors
sudo nginx -t

# Restarts Nginx
sudo service nginx start
