#!/usr/bin/env bash
# this configure Nginx server to listen on port 80.

# this will create  a link  between Nginx configuration file
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
kill "$(pgrep 'nginx' | head -l)"

